variable "availability_domain" {}
variable "compartment_id" {}
variable "image_ocid" {}
variable "shape" {}
variable "subnet_id" {}
variable "is_public_ip" {}
variable "network_security_group_ids" {}
variable "public_key" {}
variable "cloud_init" {}
variable "app_tag" {}
variable "environment" {}