variable "availability_domain" {}
variable "compartment_ocid" {}
variable "shape" {}
variable "subnet_id" {}
variable "is_public_ip" {}
variable "network_security_group_ids" {}
variable "backend_ip_address" {}
variable "app_tag" {}
variable "environment" {}